import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { PropsWithChildren } from "react";

import { QueryClientWrapper } from "@/components/query-client-wrapper";
import { ThemeProvider } from "@/components/theme-provider";
import { ThemeSwitcher } from "@/components/theme-switcher";


// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const RootLayout = ({ children }: PropsWithChildren) => {
	return (
		<html lang="en" suppressHydrationWarning>
			<head>
				<link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet' />
			</head>
			<body className={"min-h-screen font-sans"}>
				<QueryClientWrapper>
					<ThemeProvider attribute="class">
						<header className=" border-b px-6 py-4 ">
							<div className="flex items-center justify-end max-w-7xl mx-auto">
								<ThemeSwitcher className=" z-10" />

							</div>
						</header>
						{children}
					</ThemeProvider>
				</QueryClientWrapper>
			</body>
		</html>
	);
};


export default RootLayout;
